/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BrandKit {
  'outroText' : string,
  'visualStyle' : string,
  'voice' : string,
  'introText' : string,
  'aspectRatio' : string,
}
export interface CreateVideoRequest {
  'title' : string,
  'mode' : GenerationMode,
  'prompt' : string,
}
export type CreditsAmount = bigint;
export interface DashboardAnalytics {
  'avgCompletionRate' : bigint,
  'totalViews' : bigint,
  'totalVideos' : bigint,
  'totalWatchTimeHours' : bigint,
}
export type ExternalBlob = Uint8Array;
export type GenerationMode = { 'userScript' : { 'script' : string } } |
  { 'auto' : null };
export type PipelineStage = { 'voiceover' : null } |
  { 'script' : null } |
  { 'assembly' : null } |
  { 'images' : null };
export interface PublishToYouTubeRequest {
  'title' : string,
  'tags' : Array<string>,
  'description' : string,
  'visibility' : YouTubeVisibility,
}
export interface SavedScript {
  'id' : ScriptId,
  'title' : string,
  'content' : string,
  'userId' : UserId,
  'createdAt' : Timestamp,
}
export type ScriptId = bigint;
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface Subscription {
  'status' : SubscriptionStatus,
  'stripeSubscriptionId' : string,
  'createdAt' : Timestamp,
  'tier' : SubscriptionTier,
  'currentPeriodEnd' : Timestamp,
  'stripeCustomerId' : string,
}
export type SubscriptionStatus = { 'active' : null } |
  { 'cancelled' : null } |
  { 'expired' : null } |
  { 'none' : null };
export type SubscriptionTier = { 'pro' : null } |
  { 'enterprise' : null } |
  { 'starter' : null };
export interface TierConfig {
  'name' : string,
  'tier' : SubscriptionTier,
  'description' : string,
  'stripePriceId' : string,
  'creditsPerMonth' : CreditsAmount,
  'priceInCents' : bigint,
}
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = Principal;
export interface UserProfilePublic {
  'id' : UserId,
  'displayName' : string,
  'subscription' : [] | [Subscription],
  'createdAt' : Timestamp,
  'youtubeConnection' : [] | [YouTubeConnectionPublic],
  'email' : string,
  'updatedAt' : Timestamp,
  'stripeCustomerId' : [] | [string],
  'creditBalance' : CreditsAmount,
  'brandKit' : [] | [BrandKit],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VideoAnalytics {
  'completionRatePercent' : bigint,
  'videoJobId' : VideoJobId,
  'viewCount' : bigint,
  'totalWatchTimeSecs' : bigint,
  'lastViewedAt' : [] | [Timestamp],
}
export type VideoJobId = bigint;
export interface VideoJobPublic {
  'id' : VideoJobId,
  'status' : VideoJobStatus,
  'completionRatePercent' : bigint,
  'title' : string,
  'thumbnailUrl' : [] | [ExternalBlob],
  'userId' : UserId,
  'shareUrl' : [] | [string],
  'script' : [] | [string],
  'mode' : GenerationMode,
  'createdAt' : Timestamp,
  'errorMessage' : [] | [string],
  'shareToken' : [] | [string],
  'creditsSpent' : CreditsAmount,
  'updatedAt' : Timestamp,
  'viewCount' : bigint,
  'durationSeconds' : [] | [bigint],
  'prompt' : string,
  'currentStage' : [] | [PipelineStage],
  'totalWatchTimeSecs' : bigint,
  'youtubeUrl' : [] | [string],
  'youtubePublishStatus' : YouTubePublishStatus,
  'videoUrl' : [] | [ExternalBlob],
  'voiceoverUrl' : [] | [ExternalBlob],
  'lastViewedAt' : [] | [Timestamp],
}
export type VideoJobStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'processing' : null } |
  { 'failed' : { 'reason' : string } };
export interface VideoPublicView {
  'title' : string,
  'thumbnailUrl' : [] | [string],
  'videoJobId' : VideoJobId,
  'createdAt' : Timestamp,
  'description' : string,
  'viewCount' : bigint,
  'videoUrl' : [] | [string],
}
export interface YouTubeConnectionPublic {
  'channelName' : string,
  'channelId' : string,
  'refreshToken' : string,
  'connectedAt' : bigint,
  'accessToken' : string,
}
export interface YouTubeConnectionStatus {
  'channelName' : [] | [string],
  'channelId' : [] | [string],
  'connected' : boolean,
}
export type YouTubePublishStatus = { 'notPublished' : null } |
  { 'published' : null } |
  { 'publishing' : null } |
  { 'failed' : null };
export type YouTubeVisibility = { 'public' : null } |
  { 'private' : null } |
  { 'unlisted' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addCredits' : ActorMethod<[Principal, CreditsAmount], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelSubscription' : ActorMethod<[], undefined>,
  'connectYouTube' : ActorMethod<[string, string], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createSubscriptionCheckout' : ActorMethod<
    [SubscriptionTier, string, string],
    string
  >,
  'deleteScript' : ActorMethod<[ScriptId], undefined>,
  'deleteVideoJob' : ActorMethod<[VideoJobId], undefined>,
  'disconnectYouTube' : ActorMethod<[], undefined>,
  'generateShareLink' : ActorMethod<[VideoJobId], string>,
  'getBrandKit' : ActorMethod<[], [] | [BrandKit]>,
  'getCallerProfile' : ActorMethod<[], [] | [UserProfilePublic]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCreditBalance' : ActorMethod<[], CreditsAmount>,
  'getDashboardAnalytics' : ActorMethod<[], DashboardAnalytics>,
  'getPublicVideo' : ActorMethod<[string], [] | [VideoPublicView]>,
  'getScript' : ActorMethod<[ScriptId], [] | [SavedScript]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getSubscriptionTiers' : ActorMethod<[], Array<TierConfig>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfilePublic]>,
  'getVideoAnalytics' : ActorMethod<[VideoJobId], [] | [VideoAnalytics]>,
  'getVideoJob' : ActorMethod<[VideoJobId], [] | [VideoJobPublic]>,
  'getYouTubeConnection' : ActorMethod<[], YouTubeConnectionStatus>,
  'handleStripeWebhook' : ActorMethod<[string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listScripts' : ActorMethod<[], Array<SavedScript>>,
  'listUserVideoJobs' : ActorMethod<[], Array<VideoJobPublic>>,
  'publishToYouTube' : ActorMethod<
    [VideoJobId, PublishToYouTubeRequest],
    undefined
  >,
  'recordVideoEngagement' : ActorMethod<
    [VideoJobId, bigint, bigint],
    undefined
  >,
  'saveBrandKit' : ActorMethod<[BrandKit], undefined>,
  'saveCallerProfile' : ActorMethod<[string, string], undefined>,
  'saveScript' : ActorMethod<[string, string], SavedScript>,
  'setOpenAiKey' : ActorMethod<[string], undefined>,
  'setReplicateKey' : ActorMethod<[string], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'setSubscription' : ActorMethod<[Principal, Subscription], undefined>,
  'submitVideoJob' : ActorMethod<[CreateVideoRequest], VideoJobId>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateVideoJobStatus' : ActorMethod<
    [
      VideoJobId,
      [] | [PipelineStage],
      [] | [string],
      boolean,
      boolean,
      [] | [string],
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];