/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const CreditsAmount = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const SubscriptionTier = IDL.Variant({
  'pro' : IDL.Null,
  'enterprise' : IDL.Null,
  'starter' : IDL.Null,
});
export const ScriptId = IDL.Nat;
export const VideoJobId = IDL.Nat;
export const BrandKit = IDL.Record({
  'outroText' : IDL.Text,
  'visualStyle' : IDL.Text,
  'voice' : IDL.Text,
  'introText' : IDL.Text,
  'aspectRatio' : IDL.Text,
});
export const UserId = IDL.Principal;
export const SubscriptionStatus = IDL.Variant({
  'active' : IDL.Null,
  'cancelled' : IDL.Null,
  'expired' : IDL.Null,
  'none' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Subscription = IDL.Record({
  'status' : SubscriptionStatus,
  'stripeSubscriptionId' : IDL.Text,
  'createdAt' : Timestamp,
  'tier' : SubscriptionTier,
  'currentPeriodEnd' : Timestamp,
  'stripeCustomerId' : IDL.Text,
});
export const YouTubeConnectionPublic = IDL.Record({
  'channelName' : IDL.Text,
  'channelId' : IDL.Text,
  'refreshToken' : IDL.Text,
  'connectedAt' : IDL.Int,
  'accessToken' : IDL.Text,
});
export const UserProfilePublic = IDL.Record({
  'id' : UserId,
  'displayName' : IDL.Text,
  'subscription' : IDL.Opt(Subscription),
  'createdAt' : Timestamp,
  'youtubeConnection' : IDL.Opt(YouTubeConnectionPublic),
  'email' : IDL.Text,
  'updatedAt' : Timestamp,
  'stripeCustomerId' : IDL.Opt(IDL.Text),
  'creditBalance' : CreditsAmount,
  'brandKit' : IDL.Opt(BrandKit),
});
export const DashboardAnalytics = IDL.Record({
  'avgCompletionRate' : IDL.Nat,
  'totalViews' : IDL.Nat,
  'totalVideos' : IDL.Nat,
  'totalWatchTimeHours' : IDL.Nat,
});
export const VideoPublicView = IDL.Record({
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Opt(IDL.Text),
  'videoJobId' : VideoJobId,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'viewCount' : IDL.Nat,
  'videoUrl' : IDL.Opt(IDL.Text),
});
export const SavedScript = IDL.Record({
  'id' : ScriptId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'userId' : UserId,
  'createdAt' : Timestamp,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const TierConfig = IDL.Record({
  'name' : IDL.Text,
  'tier' : SubscriptionTier,
  'description' : IDL.Text,
  'stripePriceId' : IDL.Text,
  'creditsPerMonth' : CreditsAmount,
  'priceInCents' : IDL.Nat,
});
export const VideoAnalytics = IDL.Record({
  'completionRatePercent' : IDL.Nat,
  'videoJobId' : VideoJobId,
  'viewCount' : IDL.Nat,
  'totalWatchTimeSecs' : IDL.Nat,
  'lastViewedAt' : IDL.Opt(Timestamp),
});
export const VideoJobStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'processing' : IDL.Null,
  'failed' : IDL.Record({ 'reason' : IDL.Text }),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const GenerationMode = IDL.Variant({
  'userScript' : IDL.Record({ 'script' : IDL.Text }),
  'auto' : IDL.Null,
});
export const PipelineStage = IDL.Variant({
  'voiceover' : IDL.Null,
  'script' : IDL.Null,
  'assembly' : IDL.Null,
  'images' : IDL.Null,
});
export const YouTubePublishStatus = IDL.Variant({
  'notPublished' : IDL.Null,
  'published' : IDL.Null,
  'publishing' : IDL.Null,
  'failed' : IDL.Null,
});
export const VideoJobPublic = IDL.Record({
  'id' : VideoJobId,
  'status' : VideoJobStatus,
  'completionRatePercent' : IDL.Nat,
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Opt(ExternalBlob),
  'userId' : UserId,
  'shareUrl' : IDL.Opt(IDL.Text),
  'script' : IDL.Opt(IDL.Text),
  'mode' : GenerationMode,
  'createdAt' : Timestamp,
  'errorMessage' : IDL.Opt(IDL.Text),
  'shareToken' : IDL.Opt(IDL.Text),
  'creditsSpent' : CreditsAmount,
  'updatedAt' : Timestamp,
  'viewCount' : IDL.Nat,
  'durationSeconds' : IDL.Opt(IDL.Nat),
  'prompt' : IDL.Text,
  'currentStage' : IDL.Opt(PipelineStage),
  'totalWatchTimeSecs' : IDL.Nat,
  'youtubeUrl' : IDL.Opt(IDL.Text),
  'youtubePublishStatus' : YouTubePublishStatus,
  'videoUrl' : IDL.Opt(ExternalBlob),
  'voiceoverUrl' : IDL.Opt(ExternalBlob),
  'lastViewedAt' : IDL.Opt(Timestamp),
});
export const YouTubeConnectionStatus = IDL.Record({
  'channelName' : IDL.Opt(IDL.Text),
  'channelId' : IDL.Opt(IDL.Text),
  'connected' : IDL.Bool,
});
export const YouTubeVisibility = IDL.Variant({
  'public' : IDL.Null,
  'private' : IDL.Null,
  'unlisted' : IDL.Null,
});
export const PublishToYouTubeRequest = IDL.Record({
  'title' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'visibility' : YouTubeVisibility,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const CreateVideoRequest = IDL.Record({
  'title' : IDL.Text,
  'mode' : GenerationMode,
  'prompt' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addCredits' : IDL.Func([IDL.Principal, CreditsAmount], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelSubscription' : IDL.Func([], [], []),
  'connectYouTube' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createSubscriptionCheckout' : IDL.Func(
      [SubscriptionTier, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteScript' : IDL.Func([ScriptId], [], []),
  'deleteVideoJob' : IDL.Func([VideoJobId], [], []),
  'disconnectYouTube' : IDL.Func([], [], []),
  'generateShareLink' : IDL.Func([VideoJobId], [IDL.Text], []),
  'getBrandKit' : IDL.Func([], [IDL.Opt(BrandKit)], ['query']),
  'getCallerProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCreditBalance' : IDL.Func([], [CreditsAmount], ['query']),
  'getDashboardAnalytics' : IDL.Func([], [DashboardAnalytics], []),
  'getPublicVideo' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(VideoPublicView)],
      ['query'],
    ),
  'getScript' : IDL.Func([ScriptId], [IDL.Opt(SavedScript)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getSubscriptionTiers' : IDL.Func([], [IDL.Vec(TierConfig)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfilePublic)],
      ['query'],
    ),
  'getVideoAnalytics' : IDL.Func([VideoJobId], [IDL.Opt(VideoAnalytics)], []),
  'getVideoJob' : IDL.Func([VideoJobId], [IDL.Opt(VideoJobPublic)], ['query']),
  'getYouTubeConnection' : IDL.Func([], [YouTubeConnectionStatus], []),
  'handleStripeWebhook' : IDL.Func([IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listScripts' : IDL.Func([], [IDL.Vec(SavedScript)], ['query']),
  'listUserVideoJobs' : IDL.Func([], [IDL.Vec(VideoJobPublic)], ['query']),
  'publishToYouTube' : IDL.Func([VideoJobId, PublishToYouTubeRequest], [], []),
  'recordVideoEngagement' : IDL.Func([VideoJobId, IDL.Nat, IDL.Nat], [], []),
  'saveBrandKit' : IDL.Func([BrandKit], [], []),
  'saveCallerProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveScript' : IDL.Func([IDL.Text, IDL.Text], [SavedScript], []),
  'setOpenAiKey' : IDL.Func([IDL.Text], [], []),
  'setReplicateKey' : IDL.Func([IDL.Text], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'setSubscription' : IDL.Func([IDL.Principal, Subscription], [], []),
  'submitVideoJob' : IDL.Func([CreateVideoRequest], [VideoJobId], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateVideoJobStatus' : IDL.Func(
      [
        VideoJobId,
        IDL.Opt(PipelineStage),
        IDL.Opt(IDL.Text),
        IDL.Bool,
        IDL.Bool,
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const CreditsAmount = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const SubscriptionTier = IDL.Variant({
    'pro' : IDL.Null,
    'enterprise' : IDL.Null,
    'starter' : IDL.Null,
  });
  const ScriptId = IDL.Nat;
  const VideoJobId = IDL.Nat;
  const BrandKit = IDL.Record({
    'outroText' : IDL.Text,
    'visualStyle' : IDL.Text,
    'voice' : IDL.Text,
    'introText' : IDL.Text,
    'aspectRatio' : IDL.Text,
  });
  const UserId = IDL.Principal;
  const SubscriptionStatus = IDL.Variant({
    'active' : IDL.Null,
    'cancelled' : IDL.Null,
    'expired' : IDL.Null,
    'none' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Subscription = IDL.Record({
    'status' : SubscriptionStatus,
    'stripeSubscriptionId' : IDL.Text,
    'createdAt' : Timestamp,
    'tier' : SubscriptionTier,
    'currentPeriodEnd' : Timestamp,
    'stripeCustomerId' : IDL.Text,
  });
  const YouTubeConnectionPublic = IDL.Record({
    'channelName' : IDL.Text,
    'channelId' : IDL.Text,
    'refreshToken' : IDL.Text,
    'connectedAt' : IDL.Int,
    'accessToken' : IDL.Text,
  });
  const UserProfilePublic = IDL.Record({
    'id' : UserId,
    'displayName' : IDL.Text,
    'subscription' : IDL.Opt(Subscription),
    'createdAt' : Timestamp,
    'youtubeConnection' : IDL.Opt(YouTubeConnectionPublic),
    'email' : IDL.Text,
    'updatedAt' : Timestamp,
    'stripeCustomerId' : IDL.Opt(IDL.Text),
    'creditBalance' : CreditsAmount,
    'brandKit' : IDL.Opt(BrandKit),
  });
  const DashboardAnalytics = IDL.Record({
    'avgCompletionRate' : IDL.Nat,
    'totalViews' : IDL.Nat,
    'totalVideos' : IDL.Nat,
    'totalWatchTimeHours' : IDL.Nat,
  });
  const VideoPublicView = IDL.Record({
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Opt(IDL.Text),
    'videoJobId' : VideoJobId,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'viewCount' : IDL.Nat,
    'videoUrl' : IDL.Opt(IDL.Text),
  });
  const SavedScript = IDL.Record({
    'id' : ScriptId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'userId' : UserId,
    'createdAt' : Timestamp,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const TierConfig = IDL.Record({
    'name' : IDL.Text,
    'tier' : SubscriptionTier,
    'description' : IDL.Text,
    'stripePriceId' : IDL.Text,
    'creditsPerMonth' : CreditsAmount,
    'priceInCents' : IDL.Nat,
  });
  const VideoAnalytics = IDL.Record({
    'completionRatePercent' : IDL.Nat,
    'videoJobId' : VideoJobId,
    'viewCount' : IDL.Nat,
    'totalWatchTimeSecs' : IDL.Nat,
    'lastViewedAt' : IDL.Opt(Timestamp),
  });
  const VideoJobStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'processing' : IDL.Null,
    'failed' : IDL.Record({ 'reason' : IDL.Text }),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const GenerationMode = IDL.Variant({
    'userScript' : IDL.Record({ 'script' : IDL.Text }),
    'auto' : IDL.Null,
  });
  const PipelineStage = IDL.Variant({
    'voiceover' : IDL.Null,
    'script' : IDL.Null,
    'assembly' : IDL.Null,
    'images' : IDL.Null,
  });
  const YouTubePublishStatus = IDL.Variant({
    'notPublished' : IDL.Null,
    'published' : IDL.Null,
    'publishing' : IDL.Null,
    'failed' : IDL.Null,
  });
  const VideoJobPublic = IDL.Record({
    'id' : VideoJobId,
    'status' : VideoJobStatus,
    'completionRatePercent' : IDL.Nat,
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Opt(ExternalBlob),
    'userId' : UserId,
    'shareUrl' : IDL.Opt(IDL.Text),
    'script' : IDL.Opt(IDL.Text),
    'mode' : GenerationMode,
    'createdAt' : Timestamp,
    'errorMessage' : IDL.Opt(IDL.Text),
    'shareToken' : IDL.Opt(IDL.Text),
    'creditsSpent' : CreditsAmount,
    'updatedAt' : Timestamp,
    'viewCount' : IDL.Nat,
    'durationSeconds' : IDL.Opt(IDL.Nat),
    'prompt' : IDL.Text,
    'currentStage' : IDL.Opt(PipelineStage),
    'totalWatchTimeSecs' : IDL.Nat,
    'youtubeUrl' : IDL.Opt(IDL.Text),
    'youtubePublishStatus' : YouTubePublishStatus,
    'videoUrl' : IDL.Opt(ExternalBlob),
    'voiceoverUrl' : IDL.Opt(ExternalBlob),
    'lastViewedAt' : IDL.Opt(Timestamp),
  });
  const YouTubeConnectionStatus = IDL.Record({
    'channelName' : IDL.Opt(IDL.Text),
    'channelId' : IDL.Opt(IDL.Text),
    'connected' : IDL.Bool,
  });
  const YouTubeVisibility = IDL.Variant({
    'public' : IDL.Null,
    'private' : IDL.Null,
    'unlisted' : IDL.Null,
  });
  const PublishToYouTubeRequest = IDL.Record({
    'title' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'visibility' : YouTubeVisibility,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const CreateVideoRequest = IDL.Record({
    'title' : IDL.Text,
    'mode' : GenerationMode,
    'prompt' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addCredits' : IDL.Func([IDL.Principal, CreditsAmount], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelSubscription' : IDL.Func([], [], []),
    'connectYouTube' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createSubscriptionCheckout' : IDL.Func(
        [SubscriptionTier, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteScript' : IDL.Func([ScriptId], [], []),
    'deleteVideoJob' : IDL.Func([VideoJobId], [], []),
    'disconnectYouTube' : IDL.Func([], [], []),
    'generateShareLink' : IDL.Func([VideoJobId], [IDL.Text], []),
    'getBrandKit' : IDL.Func([], [IDL.Opt(BrandKit)], ['query']),
    'getCallerProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCreditBalance' : IDL.Func([], [CreditsAmount], ['query']),
    'getDashboardAnalytics' : IDL.Func([], [DashboardAnalytics], []),
    'getPublicVideo' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(VideoPublicView)],
        ['query'],
      ),
    'getScript' : IDL.Func([ScriptId], [IDL.Opt(SavedScript)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getSubscriptionTiers' : IDL.Func([], [IDL.Vec(TierConfig)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfilePublic)],
        ['query'],
      ),
    'getVideoAnalytics' : IDL.Func([VideoJobId], [IDL.Opt(VideoAnalytics)], []),
    'getVideoJob' : IDL.Func(
        [VideoJobId],
        [IDL.Opt(VideoJobPublic)],
        ['query'],
      ),
    'getYouTubeConnection' : IDL.Func([], [YouTubeConnectionStatus], []),
    'handleStripeWebhook' : IDL.Func([IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listScripts' : IDL.Func([], [IDL.Vec(SavedScript)], ['query']),
    'listUserVideoJobs' : IDL.Func([], [IDL.Vec(VideoJobPublic)], ['query']),
    'publishToYouTube' : IDL.Func(
        [VideoJobId, PublishToYouTubeRequest],
        [],
        [],
      ),
    'recordVideoEngagement' : IDL.Func([VideoJobId, IDL.Nat, IDL.Nat], [], []),
    'saveBrandKit' : IDL.Func([BrandKit], [], []),
    'saveCallerProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveScript' : IDL.Func([IDL.Text, IDL.Text], [SavedScript], []),
    'setOpenAiKey' : IDL.Func([IDL.Text], [], []),
    'setReplicateKey' : IDL.Func([IDL.Text], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'setSubscription' : IDL.Func([IDL.Principal, Subscription], [], []),
    'submitVideoJob' : IDL.Func([CreateVideoRequest], [VideoJobId], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateVideoJobStatus' : IDL.Func(
        [
          VideoJobId,
          IDL.Opt(PipelineStage),
          IDL.Opt(IDL.Text),
          IDL.Bool,
          IDL.Bool,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };