/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface VideoJobPublic {
    id: VideoJobId;
    status: VideoJobStatus;
    completionRatePercent: bigint;
    title: string;
    thumbnailUrl?: ExternalBlob;
    userId: UserId;
    shareUrl?: string;
    script?: string;
    mode: GenerationMode;
    createdAt: Timestamp;
    errorMessage?: string;
    shareToken?: string;
    creditsSpent: CreditsAmount;
    updatedAt: Timestamp;
    viewCount: bigint;
    durationSeconds?: bigint;
    prompt: string;
    currentStage?: PipelineStage;
    totalWatchTimeSecs: bigint;
    youtubeUrl?: string;
    youtubePublishStatus: YouTubePublishStatus;
    videoUrl?: ExternalBlob;
    voiceoverUrl?: ExternalBlob;
    lastViewedAt?: Timestamp;
}
export interface VideoAnalytics {
    completionRatePercent: bigint;
    videoJobId: VideoJobId;
    viewCount: bigint;
    totalWatchTimeSecs: bigint;
    lastViewedAt?: Timestamp;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface Subscription {
    status: SubscriptionStatus;
    stripeSubscriptionId: string;
    createdAt: Timestamp;
    tier: SubscriptionTier;
    currentPeriodEnd: Timestamp;
    stripeCustomerId: string;
}
export interface CreateVideoRequest {
    title: string;
    mode: GenerationMode;
    prompt: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type GenerationMode = {
    __kind__: "userScript";
    userScript: {
        script: string;
    };
} | {
    __kind__: "auto";
    auto: null;
};
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface SavedScript {
    id: ScriptId;
    title: string;
    content: string;
    userId: UserId;
    createdAt: Timestamp;
}
export interface TierConfig {
    name: string;
    tier: SubscriptionTier;
    description: string;
    stripePriceId: string;
    creditsPerMonth: CreditsAmount;
    priceInCents: bigint;
}
export type VideoJobId = bigint;
export interface YouTubeConnectionStatus {
    channelName?: string;
    channelId?: string;
    connected: boolean;
}
export interface VideoPublicView {
    title: string;
    thumbnailUrl?: string;
    videoJobId: VideoJobId;
    createdAt: Timestamp;
    description: string;
    viewCount: bigint;
    videoUrl?: string;
}
export interface PublishToYouTubeRequest {
    title: string;
    tags: Array<string>;
    description: string;
    visibility: YouTubeVisibility;
}
export interface DashboardAnalytics {
    avgCompletionRate: bigint;
    totalViews: bigint;
    totalVideos: bigint;
    totalWatchTimeHours: bigint;
}
export type CreditsAmount = bigint;
export interface BrandKit {
    outroText: string;
    visualStyle: string;
    voice: string;
    introText: string;
    aspectRatio: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type ScriptId = bigint;
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface UserProfilePublic {
    id: UserId;
    displayName: string;
    subscription?: Subscription;
    createdAt: Timestamp;
    youtubeConnection?: YouTubeConnectionPublic;
    email: string;
    updatedAt: Timestamp;
    stripeCustomerId?: string;
    creditBalance: CreditsAmount;
    brandKit?: BrandKit;
}
export type UserId = Principal;
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface YouTubeConnectionPublic {
    channelName: string;
    channelId: string;
    refreshToken: string;
    connectedAt: bigint;
    accessToken: string;
}
export type VideoJobStatus = {
    __kind__: "pending";
    pending: null;
} | {
    __kind__: "completed";
    completed: null;
} | {
    __kind__: "processing";
    processing: null;
} | {
    __kind__: "failed";
    failed: {
        reason: string;
    };
};
export enum PipelineStage {
    voiceover = "voiceover",
    script = "script",
    assembly = "assembly",
    images = "images"
}
export enum SubscriptionStatus {
    active = "active",
    cancelled = "cancelled",
    expired = "expired",
    none = "none"
}
export enum SubscriptionTier {
    pro = "pro",
    enterprise = "enterprise",
    starter = "starter"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum YouTubePublishStatus {
    notPublished = "notPublished",
    published = "published",
    publishing = "publishing",
    failed = "failed"
}
export enum YouTubeVisibility {
    public_ = "public",
    private_ = "private",
    unlisted = "unlisted"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    addCredits(user: Principal, amount: CreditsAmount): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelSubscription(): Promise<void>;
    connectYouTube(authCode: string, redirectUri: string): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createSubscriptionCheckout(tier: SubscriptionTier, successUrl: string, cancelUrl: string): Promise<string>;
    deleteScript(id: ScriptId): Promise<void>;
    deleteVideoJob(jobId: VideoJobId): Promise<void>;
    disconnectYouTube(): Promise<void>;
    generateShareLink(videoId: VideoJobId): Promise<string>;
    getBrandKit(): Promise<BrandKit | null>;
    getCallerProfile(): Promise<UserProfilePublic | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCreditBalance(): Promise<CreditsAmount>;
    getDashboardAnalytics(): Promise<DashboardAnalytics>;
    getPublicVideo(token: string): Promise<VideoPublicView | null>;
    getScript(id: ScriptId): Promise<SavedScript | null>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getSubscriptionTiers(): Promise<Array<TierConfig>>;
    getUserProfile(user: Principal): Promise<UserProfilePublic | null>;
    getVideoAnalytics(videoId: VideoJobId): Promise<VideoAnalytics | null>;
    getVideoJob(jobId: VideoJobId): Promise<VideoJobPublic | null>;
    getYouTubeConnection(): Promise<YouTubeConnectionStatus>;
    handleStripeWebhook(payload: string): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    listScripts(): Promise<Array<SavedScript>>;
    listUserVideoJobs(): Promise<Array<VideoJobPublic>>;
    publishToYouTube(videoId: VideoJobId, request: PublishToYouTubeRequest): Promise<void>;
    recordVideoEngagement(videoId: VideoJobId, watchTimeSecs: bigint, completionPercent: bigint): Promise<void>;
    saveBrandKit(kit: BrandKit): Promise<void>;
    saveCallerProfile(displayName: string, email: string): Promise<void>;
    saveScript(title: string, content: string): Promise<SavedScript>;
    setOpenAiKey(key: string): Promise<void>;
    setReplicateKey(key: string): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    setSubscription(user: Principal, subscription: Subscription): Promise<void>;
    submitVideoJob(req: CreateVideoRequest): Promise<VideoJobId>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateVideoJobStatus(jobId: VideoJobId, stage: PipelineStage | null, script: string | null, completed: boolean, failed: boolean, failReason: string | null): Promise<void>;
}
import type { BrandKit as _BrandKit, CreateVideoRequest as _CreateVideoRequest, CreditsAmount as _CreditsAmount, ExternalBlob as _ExternalBlob, GenerationMode as _GenerationMode, PipelineStage as _PipelineStage, PublishToYouTubeRequest as _PublishToYouTubeRequest, SavedScript as _SavedScript, StripeSessionStatus as _StripeSessionStatus, Subscription as _Subscription, SubscriptionStatus as _SubscriptionStatus, SubscriptionTier as _SubscriptionTier, TierConfig as _TierConfig, Timestamp as _Timestamp, UserId as _UserId, UserProfilePublic as _UserProfilePublic, UserRole as _UserRole, VideoAnalytics as _VideoAnalytics, VideoJobId as _VideoJobId, VideoJobPublic as _VideoJobPublic, VideoJobStatus as _VideoJobStatus, VideoPublicView as _VideoPublicView, YouTubeConnectionPublic as _YouTubeConnectionPublic, YouTubeConnectionStatus as _YouTubeConnectionStatus, YouTubePublishStatus as _YouTubePublishStatus, YouTubeVisibility as _YouTubeVisibility, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addCredits(arg0: Principal, arg1: CreditsAmount): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCredits(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCredits(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelSubscription(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelSubscription();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelSubscription();
            return result;
        }
    }
    async connectYouTube(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.connectYouTube(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.connectYouTube(arg0, arg1);
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createSubscriptionCheckout(arg0: SubscriptionTier, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createSubscriptionCheckout(to_candid_SubscriptionTier_n10(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSubscriptionCheckout(to_candid_SubscriptionTier_n10(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
    async deleteScript(arg0: ScriptId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteScript(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteScript(arg0);
            return result;
        }
    }
    async deleteVideoJob(arg0: VideoJobId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVideoJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVideoJob(arg0);
            return result;
        }
    }
    async disconnectYouTube(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.disconnectYouTube();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.disconnectYouTube();
            return result;
        }
    }
    async generateShareLink(arg0: VideoJobId): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateShareLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateShareLink(arg0);
            return result;
        }
    }
    async getBrandKit(): Promise<BrandKit | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBrandKit();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBrandKit();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerProfile(): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerProfile();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerProfile();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCreditBalance(): Promise<CreditsAmount> {
        if (this.processError) {
            try {
                const result = await this.actor.getCreditBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCreditBalance();
            return result;
        }
    }
    async getDashboardAnalytics(): Promise<DashboardAnalytics> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardAnalytics();
            return result;
        }
    }
    async getPublicVideo(arg0: string): Promise<VideoPublicView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicVideo(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicVideo(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getScript(arg0: ScriptId): Promise<SavedScript | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getScript(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScript(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubscriptionTiers(): Promise<Array<TierConfig>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubscriptionTiers();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubscriptionTiers();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideoAnalytics(arg0: VideoJobId): Promise<VideoAnalytics | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideoAnalytics(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideoAnalytics(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideoJob(arg0: VideoJobId): Promise<VideoJobPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideoJob(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideoJob(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getYouTubeConnection(): Promise<YouTubeConnectionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getYouTubeConnection();
                return from_candid_YouTubeConnectionStatus_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getYouTubeConnection();
            return from_candid_YouTubeConnectionStatus_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async handleStripeWebhook(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.handleStripeWebhook(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.handleStripeWebhook(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async listScripts(): Promise<Array<SavedScript>> {
        if (this.processError) {
            try {
                const result = await this.actor.listScripts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listScripts();
            return result;
        }
    }
    async listUserVideoJobs(): Promise<Array<VideoJobPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUserVideoJobs();
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUserVideoJobs();
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async publishToYouTube(arg0: VideoJobId, arg1: PublishToYouTubeRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.publishToYouTube(arg0, to_candid_PublishToYouTubeRequest_n58(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishToYouTube(arg0, to_candid_PublishToYouTubeRequest_n58(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async recordVideoEngagement(arg0: VideoJobId, arg1: bigint, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordVideoEngagement(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordVideoEngagement(arg0, arg1, arg2);
            return result;
        }
    }
    async saveBrandKit(arg0: BrandKit): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveBrandKit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveBrandKit(arg0);
            return result;
        }
    }
    async saveCallerProfile(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerProfile(arg0, arg1);
            return result;
        }
    }
    async saveScript(arg0: string, arg1: string): Promise<SavedScript> {
        if (this.processError) {
            try {
                const result = await this.actor.saveScript(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveScript(arg0, arg1);
            return result;
        }
    }
    async setOpenAiKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setOpenAiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setOpenAiKey(arg0);
            return result;
        }
    }
    async setReplicateKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setReplicateKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setReplicateKey(arg0);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async setSubscription(arg0: Principal, arg1: Subscription): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSubscription(arg0, to_candid_Subscription_n62(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSubscription(arg0, to_candid_Subscription_n62(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async submitVideoJob(arg0: CreateVideoRequest): Promise<VideoJobId> {
        if (this.processError) {
            try {
                const result = await this.actor.submitVideoJob(to_candid_CreateVideoRequest_n66(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitVideoJob(to_candid_CreateVideoRequest_n66(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateVideoJobStatus(arg0: VideoJobId, arg1: PipelineStage | null, arg2: string | null, arg3: boolean, arg4: boolean, arg5: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVideoJobStatus(arg0, to_candid_opt_n70(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n73(this._uploadFile, this._downloadFile, arg2), arg3, arg4, to_candid_opt_n73(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVideoJobStatus(arg0, to_candid_opt_n70(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n73(this._uploadFile, this._downloadFile, arg2), arg3, arg4, to_candid_opt_n73(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_GenerationMode_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GenerationMode): GenerationMode {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid_PipelineStage_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PipelineStage): PipelineStage {
    return from_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionStatus): SubscriptionStatus {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionTier_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionTier): SubscriptionTier {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Subscription_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Subscription): Subscription {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_TierConfig_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TierConfig): TierConfig {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfilePublic_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfilePublic): UserProfilePublic {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_VideoAnalytics_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VideoAnalytics): VideoAnalytics {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
async function from_candid_VideoJobPublic_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VideoJobPublic): Promise<VideoJobPublic> {
    return await from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_VideoJobStatus_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VideoJobStatus): VideoJobStatus {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function from_candid_VideoPublicView_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VideoPublicView): VideoPublicView {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_YouTubeConnectionStatus_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _YouTubeConnectionStatus): YouTubeConnectionStatus {
    return from_candid_record_n56(_uploadFile, _downloadFile, value);
}
function from_candid_YouTubePublishStatus_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _YouTubePublishStatus): YouTubePublishStatus {
    return from_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BrandKit]): BrandKit | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfilePublic]): UserProfilePublic | null {
    return value.length === 0 ? null : from_candid_UserProfilePublic_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Subscription]): Subscription | null {
    return value.length === 0 ? null : from_candid_Subscription_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_YouTubeConnectionPublic]): YouTubeConnectionPublic | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VideoPublicView]): VideoPublicView | null {
    return value.length === 0 ? null : from_candid_VideoPublicView_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SavedScript]): SavedScript | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VideoAnalytics]): VideoAnalytics | null {
    return value.length === 0 ? null : from_candid_VideoAnalytics_n38(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VideoJobPublic]): Promise<VideoJobPublic | null> {
    return value.length === 0 ? null : await from_candid_VideoJobPublic_n42(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n47(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PipelineStage]): PipelineStage | null {
    return value.length === 0 ? null : from_candid_PipelineStage_n51(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    displayName: string;
    subscription: [] | [_Subscription];
    createdAt: _Timestamp;
    youtubeConnection: [] | [_YouTubeConnectionPublic];
    email: string;
    updatedAt: _Timestamp;
    stripeCustomerId: [] | [string];
    creditBalance: _CreditsAmount;
    brandKit: [] | [_BrandKit];
}): {
    id: UserId;
    displayName: string;
    subscription?: Subscription;
    createdAt: Timestamp;
    youtubeConnection?: YouTubeConnectionPublic;
    email: string;
    updatedAt: Timestamp;
    stripeCustomerId?: string;
    creditBalance: CreditsAmount;
    brandKit?: BrandKit;
} {
    return {
        id: value.id,
        displayName: value.displayName,
        subscription: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.subscription)),
        createdAt: value.createdAt,
        youtubeConnection: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.youtubeConnection)),
        email: value.email,
        updatedAt: value.updatedAt,
        stripeCustomerId: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.stripeCustomerId)),
        creditBalance: value.creditBalance,
        brandKit: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.brandKit))
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _SubscriptionStatus;
    stripeSubscriptionId: string;
    createdAt: _Timestamp;
    tier: _SubscriptionTier;
    currentPeriodEnd: _Timestamp;
    stripeCustomerId: string;
}): {
    status: SubscriptionStatus;
    stripeSubscriptionId: string;
    createdAt: Timestamp;
    tier: SubscriptionTier;
    currentPeriodEnd: Timestamp;
    stripeCustomerId: string;
} {
    return {
        status: from_candid_SubscriptionStatus_n19(_uploadFile, _downloadFile, value.status),
        stripeSubscriptionId: value.stripeSubscriptionId,
        createdAt: value.createdAt,
        tier: from_candid_SubscriptionTier_n21(_uploadFile, _downloadFile, value.tier),
        currentPeriodEnd: value.currentPeriodEnd,
        stripeCustomerId: value.stripeCustomerId
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    thumbnailUrl: [] | [string];
    videoJobId: _VideoJobId;
    createdAt: _Timestamp;
    description: string;
    viewCount: bigint;
    videoUrl: [] | [string];
}): {
    title: string;
    thumbnailUrl?: string;
    videoJobId: VideoJobId;
    createdAt: Timestamp;
    description: string;
    viewCount: bigint;
    videoUrl?: string;
} {
    return {
        title: value.title,
        thumbnailUrl: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.thumbnailUrl)),
        videoJobId: value.videoJobId,
        createdAt: value.createdAt,
        description: value.description,
        viewCount: value.viewCount,
        videoUrl: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.videoUrl))
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    tier: _SubscriptionTier;
    description: string;
    stripePriceId: string;
    creditsPerMonth: _CreditsAmount;
    priceInCents: bigint;
}): {
    name: string;
    tier: SubscriptionTier;
    description: string;
    stripePriceId: string;
    creditsPerMonth: CreditsAmount;
    priceInCents: bigint;
} {
    return {
        name: value.name,
        tier: from_candid_SubscriptionTier_n21(_uploadFile, _downloadFile, value.tier),
        description: value.description,
        stripePriceId: value.stripePriceId,
        creditsPerMonth: value.creditsPerMonth,
        priceInCents: value.priceInCents
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completionRatePercent: bigint;
    videoJobId: _VideoJobId;
    viewCount: bigint;
    totalWatchTimeSecs: bigint;
    lastViewedAt: [] | [_Timestamp];
}): {
    completionRatePercent: bigint;
    videoJobId: VideoJobId;
    viewCount: bigint;
    totalWatchTimeSecs: bigint;
    lastViewedAt?: Timestamp;
} {
    return {
        completionRatePercent: value.completionRatePercent,
        videoJobId: value.videoJobId,
        viewCount: value.viewCount,
        totalWatchTimeSecs: value.totalWatchTimeSecs,
        lastViewedAt: record_opt_to_undefined(from_candid_opt_n40(_uploadFile, _downloadFile, value.lastViewedAt))
    };
}
async function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _VideoJobId;
    status: _VideoJobStatus;
    completionRatePercent: bigint;
    title: string;
    thumbnailUrl: [] | [_ExternalBlob];
    userId: _UserId;
    shareUrl: [] | [string];
    script: [] | [string];
    mode: _GenerationMode;
    createdAt: _Timestamp;
    errorMessage: [] | [string];
    shareToken: [] | [string];
    creditsSpent: _CreditsAmount;
    updatedAt: _Timestamp;
    viewCount: bigint;
    durationSeconds: [] | [bigint];
    prompt: string;
    currentStage: [] | [_PipelineStage];
    totalWatchTimeSecs: bigint;
    youtubeUrl: [] | [string];
    youtubePublishStatus: _YouTubePublishStatus;
    videoUrl: [] | [_ExternalBlob];
    voiceoverUrl: [] | [_ExternalBlob];
    lastViewedAt: [] | [_Timestamp];
}): Promise<{
    id: VideoJobId;
    status: VideoJobStatus;
    completionRatePercent: bigint;
    title: string;
    thumbnailUrl?: ExternalBlob;
    userId: UserId;
    shareUrl?: string;
    script?: string;
    mode: GenerationMode;
    createdAt: Timestamp;
    errorMessage?: string;
    shareToken?: string;
    creditsSpent: CreditsAmount;
    updatedAt: Timestamp;
    viewCount: bigint;
    durationSeconds?: bigint;
    prompt: string;
    currentStage?: PipelineStage;
    totalWatchTimeSecs: bigint;
    youtubeUrl?: string;
    youtubePublishStatus: YouTubePublishStatus;
    videoUrl?: ExternalBlob;
    voiceoverUrl?: ExternalBlob;
    lastViewedAt?: Timestamp;
}> {
    return {
        id: value.id,
        status: from_candid_VideoJobStatus_n44(_uploadFile, _downloadFile, value.status),
        completionRatePercent: value.completionRatePercent,
        title: value.title,
        thumbnailUrl: record_opt_to_undefined(await from_candid_opt_n46(_uploadFile, _downloadFile, value.thumbnailUrl)),
        userId: value.userId,
        shareUrl: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.shareUrl)),
        script: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.script)),
        mode: from_candid_GenerationMode_n48(_uploadFile, _downloadFile, value.mode),
        createdAt: value.createdAt,
        errorMessage: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.errorMessage)),
        shareToken: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.shareToken)),
        creditsSpent: value.creditsSpent,
        updatedAt: value.updatedAt,
        viewCount: value.viewCount,
        durationSeconds: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.durationSeconds)),
        prompt: value.prompt,
        currentStage: record_opt_to_undefined(from_candid_opt_n50(_uploadFile, _downloadFile, value.currentStage)),
        totalWatchTimeSecs: value.totalWatchTimeSecs,
        youtubeUrl: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.youtubeUrl)),
        youtubePublishStatus: from_candid_YouTubePublishStatus_n53(_uploadFile, _downloadFile, value.youtubePublishStatus),
        videoUrl: record_opt_to_undefined(await from_candid_opt_n46(_uploadFile, _downloadFile, value.videoUrl)),
        voiceoverUrl: record_opt_to_undefined(await from_candid_opt_n46(_uploadFile, _downloadFile, value.voiceoverUrl)),
        lastViewedAt: record_opt_to_undefined(from_candid_opt_n40(_uploadFile, _downloadFile, value.lastViewedAt))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    channelName: [] | [string];
    channelId: [] | [string];
    connected: boolean;
}): {
    channelName?: string;
    channelId?: string;
    connected: boolean;
} {
    return {
        channelName: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.channelName)),
        channelId: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.channelId)),
        connected: value.connected
    };
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    cancelled: null;
} | {
    expired: null;
} | {
    none: null;
}): SubscriptionStatus {
    return "active" in value ? SubscriptionStatus.active : "cancelled" in value ? SubscriptionStatus.cancelled : "expired" in value ? SubscriptionStatus.expired : "none" in value ? SubscriptionStatus.none : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pro: null;
} | {
    enterprise: null;
} | {
    starter: null;
}): SubscriptionTier {
    return "pro" in value ? SubscriptionTier.pro : "enterprise" in value ? SubscriptionTier.enterprise : "starter" in value ? SubscriptionTier.starter : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n33(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    processing: null;
} | {
    failed: {
        reason: string;
    };
}): {
    __kind__: "pending";
    pending: null;
} | {
    __kind__: "completed";
    completed: null;
} | {
    __kind__: "processing";
    processing: null;
} | {
    __kind__: "failed";
    failed: {
        reason: string;
    };
} {
    return "pending" in value ? {
        __kind__: "pending",
        pending: value.pending
    } : "completed" in value ? {
        __kind__: "completed",
        completed: value.completed
    } : "processing" in value ? {
        __kind__: "processing",
        processing: value.processing
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userScript: {
        script: string;
    };
} | {
    auto: null;
}): {
    __kind__: "userScript";
    userScript: {
        script: string;
    };
} | {
    __kind__: "auto";
    auto: null;
} {
    return "userScript" in value ? {
        __kind__: "userScript",
        userScript: value.userScript
    } : "auto" in value ? {
        __kind__: "auto",
        auto: value.auto
    } : value;
}
function from_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    voiceover: null;
} | {
    script: null;
} | {
    assembly: null;
} | {
    images: null;
}): PipelineStage {
    return "voiceover" in value ? PipelineStage.voiceover : "script" in value ? PipelineStage.script : "assembly" in value ? PipelineStage.assembly : "images" in value ? PipelineStage.images : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notPublished: null;
} | {
    published: null;
} | {
    publishing: null;
} | {
    failed: null;
}): YouTubePublishStatus {
    return "notPublished" in value ? YouTubePublishStatus.notPublished : "published" in value ? YouTubePublishStatus.published : "publishing" in value ? YouTubePublishStatus.publishing : "failed" in value ? YouTubePublishStatus.failed : value;
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TierConfig>): Array<TierConfig> {
    return value.map((x)=>from_candid_TierConfig_n35(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VideoJobPublic>): Promise<Array<VideoJobPublic>> {
    return await Promise.all(value.map(async (x)=>await from_candid_VideoJobPublic_n42(_uploadFile, _downloadFile, x)));
}
function to_candid_CreateVideoRequest_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateVideoRequest): _CreateVideoRequest {
    return to_candid_record_n67(_uploadFile, _downloadFile, value);
}
function to_candid_GenerationMode_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GenerationMode): _GenerationMode {
    return to_candid_variant_n69(_uploadFile, _downloadFile, value);
}
function to_candid_PipelineStage_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PipelineStage): _PipelineStage {
    return to_candid_variant_n72(_uploadFile, _downloadFile, value);
}
function to_candid_PublishToYouTubeRequest_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PublishToYouTubeRequest): _PublishToYouTubeRequest {
    return to_candid_record_n59(_uploadFile, _downloadFile, value);
}
function to_candid_SubscriptionStatus_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionStatus): _SubscriptionStatus {
    return to_candid_variant_n65(_uploadFile, _downloadFile, value);
}
function to_candid_SubscriptionTier_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionTier): _SubscriptionTier {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Subscription_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Subscription): _Subscription {
    return to_candid_record_n63(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_YouTubeVisibility_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: YouTubeVisibility): _YouTubeVisibility {
    return to_candid_variant_n61(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PipelineStage | null): [] | [_PipelineStage] {
    return value === null ? candid_none() : candid_some(to_candid_PipelineStage_n71(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    tags: Array<string>;
    description: string;
    visibility: YouTubeVisibility;
}): {
    title: string;
    tags: Array<string>;
    description: string;
    visibility: _YouTubeVisibility;
} {
    return {
        title: value.title,
        tags: value.tags,
        description: value.description,
        visibility: to_candid_YouTubeVisibility_n60(_uploadFile, _downloadFile, value.visibility)
    };
}
function to_candid_record_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: SubscriptionStatus;
    stripeSubscriptionId: string;
    createdAt: Timestamp;
    tier: SubscriptionTier;
    currentPeriodEnd: Timestamp;
    stripeCustomerId: string;
}): {
    status: _SubscriptionStatus;
    stripeSubscriptionId: string;
    createdAt: _Timestamp;
    tier: _SubscriptionTier;
    currentPeriodEnd: _Timestamp;
    stripeCustomerId: string;
} {
    return {
        status: to_candid_SubscriptionStatus_n64(_uploadFile, _downloadFile, value.status),
        stripeSubscriptionId: value.stripeSubscriptionId,
        createdAt: value.createdAt,
        tier: to_candid_SubscriptionTier_n10(_uploadFile, _downloadFile, value.tier),
        currentPeriodEnd: value.currentPeriodEnd,
        stripeCustomerId: value.stripeCustomerId
    };
}
function to_candid_record_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    mode: GenerationMode;
    prompt: string;
}): {
    title: string;
    mode: _GenerationMode;
    prompt: string;
} {
    return {
        title: value.title,
        mode: to_candid_GenerationMode_n68(_uploadFile, _downloadFile, value.mode),
        prompt: value.prompt
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionTier): {
    pro: null;
} | {
    enterprise: null;
} | {
    starter: null;
} {
    return value == SubscriptionTier.pro ? {
        pro: null
    } : value == SubscriptionTier.enterprise ? {
        enterprise: null
    } : value == SubscriptionTier.starter ? {
        starter: null
    } : value;
}
function to_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: YouTubeVisibility): {
    public: null;
} | {
    private: null;
} | {
    unlisted: null;
} {
    return value == YouTubeVisibility.public ? {
        public_: null
    } : value == YouTubeVisibility.private ? {
        private_: null
    } : value == YouTubeVisibility.unlisted ? {
        unlisted: null
    } : value;
}
function to_candid_variant_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionStatus): {
    active: null;
} | {
    cancelled: null;
} | {
    expired: null;
} | {
    none: null;
} {
    return value == SubscriptionStatus.active ? {
        active: null
    } : value == SubscriptionStatus.cancelled ? {
        cancelled: null
    } : value == SubscriptionStatus.expired ? {
        expired: null
    } : value == SubscriptionStatus.none ? {
        none: null
    } : value;
}
function to_candid_variant_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "userScript";
    userScript: {
        script: string;
    };
} | {
    __kind__: "auto";
    auto: null;
}): {
    userScript: {
        script: string;
    };
} | {
    auto: null;
} {
    return value.__kind__ === "userScript" ? {
        userScript: value.userScript
    } : value.__kind__ === "auto" ? {
        auto: value.auto
    } : value;
}
function to_candid_variant_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PipelineStage): {
    voiceover: null;
} | {
    script: null;
} | {
    assembly: null;
} | {
    images: null;
} {
    return value == PipelineStage.voiceover ? {
        voiceover: null
    } : value == PipelineStage.script ? {
        script: null
    } : value == PipelineStage.assembly ? {
        assembly: null
    } : value == PipelineStage.images ? {
        images: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
